### ISSUE TITLE
Статистика показывает некорректные данные

### ISSUE THREAD

**Issue by vladqa** [AlexeyManikin/domain_statistic#13]
Я захожу пару раз в неделю на firststat, чтоб посмотреть прирост доменов у нас и основных конкуретнов. 

Сейчас я вижу, что за прошедший месяц у некоторых других хостингов прирост равен общему числу доменов, что некорректно и лишает меня возможности порадоваться за Бегет.

Скриншот прилагаю
![firststat-stats-fuckup](https://cloud.githubusercontent.com/assets/1562113/26361546/023fa6ce-3fe4-11e7-9949-a90d93342dc4.png)

**Comment by AlexeyManikin** [comment]
Исправили.
