### ISSUE TITLE
Перестал работать manikin.beget.ru

### ISSUE THREAD

**Issue by nebuchad908** [AlexeyManikin/domain_statistic#14]
Пользуюсь им для получения данных, но что-то он перестал работать.

**Comment by AlexeyManikin** [comment]
А какие данные используете для подключения ?

**Comment by nebuchad908** [comment]
Приветствую.

~# mysql -hmanikin.beget.ru -P3311 -uread_only -pread_only
ERROR 2003 (HY000): Can't connect to MySQL server on 'manikin.beget.ru' (111)

**Comment by LokusWB** [comment]
Приветствую,
аналогично не могу подключиться...
Очень полезный проект делаете, очень хочется продолжить им пользоваться...

**Comment by AlexeyManikin** [comment]
Исправил:

mysql -hmanikin.beget.ru -P3306 -uread_only -pread_only

поменял порт на 3306
