### ISSUE TITLE
дамп

### ISSUE THREAD

**Issue by akmua** [AlexeyManikin/domain_statistic#15]
Здравствуйте,
Можно ли дамп бд?
спасибо

**Comment by AlexeyManikin** [comment]
Да конечно, сейчас сделаю.

**Comment by akmua** [comment]
ок. спасибо

**Comment by AlexeyManikin** [comment]
manikin : /opt/ssd [0] # mysqldump -h 127.0.0.1 domain_statistic > domain_statistic.sql
manikin : /opt/ssd [0] # du -sh domain_statistic.sql
72G     domain_statistic.sql
manikin : /opt/ssd [0] # tar -czf domain_statistic.sql.tar.zip domain_statistic.sql
manikin : /opt/ssd [0] # du -sh domain_statistic.sql.tar.zip
9.2G    domain_statistic.sql.tar.zip
manikin : /opt/ssd [0] # 

дайте FTP куда залить дамп

**Comment by akmua** [comment]
я отправил вам линк на свой гугл диск на имейл manikin@beget.ru

**Comment by akmua** [comment]
правильно ли я указал Ваш имейл?

**Comment by akmua** [comment]
в случае чего мой имейл arun.mishra.ua@gmail.com

**Comment by akmua** [comment]
почему то gmail инфо автоответа что нет такого пользователя отправил в спам и не знал что Вы не получили линк. отправил теперь по адресу amanikin@ .

**Comment by AlexeyManikin** [comment]
alexey@beget.ru

**Comment by akmua** [comment]
я не получил дамп?
